steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/jet-airbase-builder:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/jet-airbase-builder:1.8'
  - '-f'
  - './jet/Dockerfile_airbase-builder'
  - './jet'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Push jet-airbase-builder"
    [[ "$BRANCH_NAME" == "master" ]] && docker push gcr.io/$PROJECT_ID/jet-airbase-builder:latest
    [[ "$BRANCH_NAME" == "master" ]] && docker push gcr.io/$PROJECT_ID/jet-airbase-builder:1.8
