steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t gcr.io/$PROJECT_ID/jet-airbase-builder'
    - '-f ./jet/Dockerfile_airbase'
    - './jet'

images:
- 'gcr.io/$PROJECT_ID/jet-airbase-builder'
